<?php
/**
 * Integration test fixture helper — copies real fixture JPEGs into the test
 * uploads dir and registers them as WP attachments so the full PHP pipeline
 * (indexer + repository + search) can run against them.
 *
 * @package Pixel_Scout
 */

require_once dirname( __DIR__ ) . '/unit/class-testcase.php';

/**
 * Base class for integration tests that need real image files on disk.
 */
abstract class Pixel_Scout_Integration_TestCase extends Pixel_Scout_TestCase {

	/**
	 * Track files created so we can clean up.
	 *
	 * @var array<string>
	 */
	protected array $temp_files = array();

	/**
	 * Resolve the fixtures dir once per class.
	 *
	 * @var string
	 */
	protected static string $fixtures_dir;

	/**
	 * Resolve the fixture root.
	 *
	 * @return void
	 */
	public static function setUpBeforeClass(): void {
		parent::setUpBeforeClass();
		self::$fixtures_dir = dirname( __DIR__ ) . '/fixtures/images';
	}

	/**
	 * Skip the test class if fixtures are missing.
	 *
	 * @return void
	 */
	public function setUp(): void {
		parent::setUp();
		if ( ! file_exists( self::$fixtures_dir . '/001.jpg' ) ) {
			$this->markTestSkipped( 'Fixture images not downloaded. Run: composer fixtures' );
		}
	}

	/**
	 * Drop any files written during the test.
	 *
	 * @return void
	 */
	public function tearDown(): void {
		foreach ( $this->temp_files as $path ) {
			if ( file_exists( $path ) ) {
				wp_delete_file( $path );
			}
		}
		$this->temp_files = array();
		parent::tearDown();
	}

	/**
	 * Resolve a fixture file path by Picsum index.
	 *
	 * @param int $id 1-based fixture index.
	 *
	 * @return string Absolute path. Caller must verify with file_exists.
	 */
	protected function fixture_path( int $id ): string {
		return sprintf( '%s/%03d.jpg', self::$fixtures_dir, $id );
	}

	/**
	 * Copy a fixture into the uploads dir and register it as an attachment.
	 *
	 * @param int    $fixture_id Fixture index 1-25.
	 * @param string $variant    Optional variant suffix appended to filename.
	 *
	 * @return int Attachment ID.
	 */
	protected function attach_fixture( int $fixture_id, string $variant = '' ): int {
		$src = $this->fixture_path( $fixture_id );
		$this->assertFileExists( $src, "Fixture {$fixture_id} missing" );

		$uploads  = wp_upload_dir();
		$basename = sprintf( '%03d%s.jpg', $fixture_id, '' !== $variant ? "_{$variant}" : '' );
		$dest     = trailingslashit( $uploads['path'] ) . wp_unique_filename( $uploads['path'], $basename );
		copy( $src, $dest );
		$this->temp_files[] = $dest;

		$attachment_id = wp_insert_attachment(
			array(
				'post_mime_type' => 'image/jpeg',
				'post_title'     => sprintf( 'Fixture %03d %s', $fixture_id, $variant ),
				'post_content'   => '',
				'post_status'    => 'inherit',
			),
			$dest
		);
		$this->assertIsInt( $attachment_id );
		$this->assertGreaterThan( 0, $attachment_id );

		require_once ABSPATH . 'wp-admin/includes/image.php';
		$metadata = wp_generate_attachment_metadata( $attachment_id, $dest );
		wp_update_attachment_metadata( $attachment_id, $metadata );

		return (int) $attachment_id;
	}

	/**
	 * Attach a variant generated by transforming a fixture image via GD.
	 *
	 * Supported variants: `upscale`, `downscale`, `blur`, `compressed`,
	 * `png` (re-encode), `webp` (re-encode).
	 *
	 * @param int    $fixture_id Fixture index.
	 * @param string $variant    Variant kind.
	 *
	 * @return int Attachment ID.
	 */
	protected function attach_variant( int $fixture_id, string $variant ): int {
		$src = $this->fixture_path( $fixture_id );
		$gd  = imagecreatefromjpeg( $src );

		$ext  = 'jpg';
		$mime = 'image/jpeg';

		switch ( $variant ) {
			case 'upscale':
				$w     = imagesx( $gd ) * 2;
				$h     = imagesy( $gd ) * 2;
				$dst   = imagescale( $gd, $w, $h );
				imagedestroy( $gd );
				$gd    = $dst;
				break;
			case 'downscale':
				$w     = max( 1, (int) ( imagesx( $gd ) / 2 ) );
				$h     = max( 1, (int) ( imagesy( $gd ) / 2 ) );
				$dst   = imagescale( $gd, $w, $h );
				imagedestroy( $gd );
				$gd    = $dst;
				break;
			case 'blur':
				imagefilter( $gd, IMG_FILTER_GAUSSIAN_BLUR );
				imagefilter( $gd, IMG_FILTER_GAUSSIAN_BLUR );
				break;
			case 'compressed':
				// JPEG quality 10 — heavy artifacts.
				break;
			case 'png':
				$ext  = 'png';
				$mime = 'image/png';
				break;
			case 'webp':
				$ext  = 'webp';
				$mime = 'image/webp';
				break;
			default:
				imagedestroy( $gd );
				$this->fail( "Unknown variant: {$variant}" );
		}

		$uploads  = wp_upload_dir();
		$basename = sprintf( '%03d_%s.%s', $fixture_id, $variant, $ext );
		$dest     = trailingslashit( $uploads['path'] ) . wp_unique_filename( $uploads['path'], $basename );

		if ( 'png' === $ext ) {
			imagepng( $gd, $dest );
		} elseif ( 'webp' === $ext ) {
			imagewebp( $gd, $dest, 80 );
		} elseif ( 'compressed' === $variant ) {
			imagejpeg( $gd, $dest, 10 );
		} else {
			imagejpeg( $gd, $dest, 90 );
		}
		imagedestroy( $gd );
		$this->temp_files[] = $dest;

		$attachment_id = wp_insert_attachment(
			array(
				'post_mime_type' => $mime,
				'post_title'     => sprintf( 'Fixture %03d (%s)', $fixture_id, $variant ),
				'post_content'   => '',
				'post_status'    => 'inherit',
			),
			$dest
		);

		require_once ABSPATH . 'wp-admin/includes/image.php';
		$metadata = wp_generate_attachment_metadata( $attachment_id, $dest );
		wp_update_attachment_metadata( $attachment_id, $metadata );

		return (int) $attachment_id;
	}

	/**
	 * Copy a fixture twice — same bytes, two attachments. Used for exact-match
	 * duplicate detection (matching file_hash).
	 *
	 * @param int $fixture_id Fixture index.
	 *
	 * @return array{0: int, 1: int} Attachment IDs.
	 */
	protected function attach_fixture_twice( int $fixture_id ): array {
		return array(
			$this->attach_fixture( $fixture_id, 'a' ),
			$this->attach_fixture( $fixture_id, 'b' ),
		);
	}
}
